In [36]:
import pandas as  pd
df=pd.read_csv("Startups1project.csv")
df.head()

   R&D Spend  Administration  Marketing Spend     Profit
0   165349.2       136897.80         471784.1  192261.83
1   162597.7       151377.60         443898.5  191792.06
2   153441.5       101145.50         407934.5  191050.39
3   144372.4       118671.90         383199.6  182901.99
4   142107.3        91391.77         366168.4  166187.94

In [37]:
df.isnull().sum()

R&D Spend          0
Administration     0
Marketing Spend    0
Profit             0
dtype: int64

In [38]:
X=df.drop("Profit",axis=1)
y=df["Profit"]

In [39]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [40]:
from sklearn.linear_model import LinearRegression
model=LinearRegression()
model.fit(X_train,y_train)

LinearRegression()

In [41]:
score=model.score(X_test,y_test)
print("score:",score)

score: 0.9237976669641025

In [42]:
prediction = model.predict([[160000, 130000, 300000]])
print("Profit prédit:", prediction)

Profit prédit: [188849.02637163]

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

In [43]:
df = df.drop("Marketing Spend", axis=1)